apiVersion: v1
kind: Service
metadata:
  labels:
    run: chronograf
  name: chronograf
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10000
  selector:
    run: chronograf
  type: LoadBalancer
