apiVersion: v1
kind: Service
metadata:
  labels:
    run: chronograf
  name: chronograf
spec:
  ports:
  - nodePort: 30885
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    run: chronograf
  type: LoadBalancer
