apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: macat/sense-collector:v4
        env:
        - name: AMPQ_HOST
          valueFrom:
            secretKeyRef:
              name: sensecrets
              key: ampqhost
        - name: INFLUX_HOST
          value: http://influxdb:8086
        - name: INFLUX_USER
          value: sensewrite
        - name: INFLUX_PASS
          valueFrom:
            secretKeyRef:
              name: sensecrets
              key: sensewritepass
