apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxweb
spec:
  ports:
  - name: web
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxweb
  type: LoadBalancer
