apiVersion: v1
kind: Service
metadata:
  labels:
    run: influxdb
  name: influxdb
spec:
  ports:
  - name: port-1
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: port-2
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    run: influxdb
  type: ClusterIP
