apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-eb32506a
    fsType: ext4
