apiVersion: v1
kind: Service
metadata:
  labels:
    app: sense
  name: sense-rabbitmq-mgmt
spec:
  selector:
    app: sense
    component: rabbitmq
  type: NodePort
  ports:
  - name: "mqtt"
    protocol: "TCP"
    port: 1883
  - name: "rabbit"
    protocol: "TCP"
    port: 5672
  - name: "management"
    protocol: "TCP"
    port: 15672
