apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sense
  name: sense-rabbitmq
spec:
  replicas: 1
  selector:
    app: sense
    component: rabbitmq
  template:
    metadata:
      labels:
        app: sense
        component: rabbitmq
    spec:
      containers:
      - image: macat/rabbitmqtt:3.6.1-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 1883
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: sensecrets
              key: rabbitmquser
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: sensecrets
              key: rabbitmqpass
